region             = "eu-west-1"
vpc_cidr           = "10.0.0.0/16"
subnet_1_cidr      = "10.0.1.0/24"
subnet_2_cidr      = "10.0.2.0/24"
my_ip_cidr         = ["172.58.178.139/32"]
instance_ami       = "ami-01dd271720c1ba44f"
instance_keyname   = "techbleat_2023"
instance_type      = "t2.micro"
subnet_id          = ["aws_subnet.subnet_2.id"]
instance_count     = 1
dynamodb_statelock = "dev_terraform_statefile_lock"
default_tags = {
  "Name"        = "Dev Application Server"
  "Environment" = "Development"
  "Owner"       = "Mr. Dolittle"
  "Can_destroy" = "Yes"
} 
subnet_1_tag = "Dev App Subnet 1"
subnet_2_tag = "Dev App Subnet 2"
availability_zones = ["eu-west-1b"]
